project:
  type: default
  output-dir: "_output"
  #post-render: 
  #  - Rscript src/utils/move_output_dir.R
  # うまく機能しない

format:
  html:
    toc: true
    number-sections: true

bibliography: references/main.bib
csl: references/styles/apa.csl
# suppress-bibliography: false  # 参考文献を非表示にする場合はtrueにする

python:
  conda: ".project_env"

